version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_NAME=efe
      - POSTGRES_DB=project2
    ports:
      - '6555:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Mount schema.sql file
volumes:
  db:
    driver: local
